name: .NET Core

on:
  push:
    branches: [ master ]
    tags: '**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0-rc.2.20475.5
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Get version
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: echo "::set-env name=VERSION::$(git describe --tags --dirty)"
    - name: Pack
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: dotnet pack -c Release -o artifacts/ -p:Version=$VERSION
    - name: Push
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push artifacts/**.nupkg -s nuget.org --api-key ${{secrets.NUGET_API_KEY}}
